### ISSUE TITLE
Use node-id instead of uuid for indexing  network elements

### ISSUE THREAD

**Issue by oscargdd** [ietf-ivy-wg/network-inventory-yang#18]
[RFC 8345](https://datatracker.ietf.org/doc/rfc8345/https://datatracker.ietf.org/doc/rfc8345/) uses node-id for the indexing of the nodes.  It would be better to have the same convention. Either reuse the node-id type, or use inet:uri. This way it is not restricted to the use of uuids.

```
typedef node-id {
       type inet:uri;
       description
         "Identifier for a node.  The precise structure of the node-id
          will be up to the implementation.  For example, some
          implementations MAY pick a URI that includes the network-id
          as part of the path.  The identifier SHOULD be chosen
          such that the same node in a real network topology will
          always be identified through the same identifier, even if
          the data model is instantiated in separate datastores.  An
          implementation MAY choose to capture semantics in the
          identifier -- for example, to indicate the type of node.";
     }
```

**Comment by italobusi** [comment]
**[2024-01-17 Network Inventory weekly call](https://github.com/ietf-ivy-wg/network-inventory-yang/blob/main/minutes/minutes-2024-01-17.md)**

The list keys used to be UUID in the CCAMP WG draft but the ne-id and component-id have been defined as string, with the plan to re-discuss their types at a later stage

Jan: strings are hard to interpret but keys are intended just to identify something so they do not need to be interpreted

Agreed to keep the ne-id and component-id as string to keep the model very flexible (URI and UUID are also strings)
