### ISSUE TITLE
Refine NE assembly-id attribute

### ISSUE THREAD

**Issue by italobusi** [ietf-ivy-wg/network-inventory-yang#33]
Refine the name and description of the assembly-id attribute for the NE

**Comment by YuChaode** [comment]
For part-number, it is really not needed for NE. 
And for assembly-id, i am wandering whether we need this id or not. Currently we have ne-id, uuid, asset-id and URI defined in the current model, i think it is sufficient for NE. And for this terminology of assembly-id, there is not a common understanding in transport industry. 
so i  propose to remove part-number instead of refining it to assembly-id.

**Comment by lana-wu** [comment]
I think "assembly-id" is confusing. I suggest that "model-name" in RFC 8348 be reused.

**Comment by italobusi** [comment]
I am ok with "model-name" but I am also wondering what would be the difference between "model-name" and "product-name" ...

IMHO, we have two options:
1. remove "asset-id" and keep "product-name"
2. remove both "product-name" and "asset-id" and add "model-name"

I have a slight preference for option 1 but I can live with option 2 as well

**Comment by lana-wu** [comment]
It seems to me that "asset-id" is user-assigned tracking identifier for a component, or NE, or a rack , but "product-name" is vendor-specific?
Instead of "assembly-id", my suggestion is for "product-name".

**Comment by dieterbeller** [comment]
It is still unclear to me what the NE assembly-id attribute should reflect. Is the meaning an assembly or shelf kit composed of the NE's main shelf and several necessary HW entities? If so, the assembly or shelf kit should be modeled like any other HW component and should have a least a part number and an optional name as it is an order-able item. Or, is it the intention to model the inventory data of all these components forming the assembly or shelf kit as separate items with their component specific inventory data?

**Comment by italobusi** [comment]
> It seems to me that "asset-id" is user-assigned tracking identifier for a component, or NE, or a rack , but "product-name" is vendor-specific? I think "asset-id" and "product-name" are not equivalent. Instead of "assembly-id", my suggestion is for "product-name".

Sorry, I made a confusion between 'asset-id' and 'assembly-id' :(

I have amended my comment as:

> IMHO, we have two options:
> 
> 1. remove the "assembly-id" attribute and keep the "product-name" attribute
> 2. remove both the "product-name" and "assembly-id" attributes and add a new "model-name" attribute

**Comment by italobusi** [comment]
**[2024-02-21 Base Network Inventory weekly call](https://demo.hedgedoc.org/cQyswfIUT4WbnkvvbvjQ1Q)**

The following attributes have been agreed:

- product-name as "The vendor-specific and human-interpretable string describing the network element type. It is expected that vendors assign unique product names to different component types within the scope of the vendor."

- serial-number as "The vendor-specific serial number of the network element instance. It is expected that vendors assign unique serial numbers to different component instances within the scope of the product name."

- [ ] @YuChaode : update the draft and the model accordingly

**Comment by italobusi** [comment]
**[2024-03-06 Base Network Inventory weekly call](https://github.com/ietf-ivy-wg/network-inventory-yang/blob/main/minutes/minutes-2024-03-06.md)**

The YANG descriptions in the I-D version uploaded for IETF 119 are not fully aligned with the descriptions agreed during the call on February 21, 2024

- [ ] @YuChaode update the definitions in the YANG model to align with the definitions in [2024-02-21 Base Network Inventory weekly call](https://github.com/ietf-ivy-wg/network-inventory-yang/blob/main/minutes/minutes-2024-02-21.md)

**Comment by italobusi** [comment]
Closed with 683ea0729a10a841b3fa7de3ec57eb8f33920e0c
