### ISSUE TITLE
ALMO and DMALMO Terminology alignment definition

### ISSUE THREAD

**Issue by marisolpalmero** [ietf-ivy-wg/network-inventory-yang#38]
As per conversations in the IVY working group, the authors of [ps-ALMO](https://datatracker.ietf.org/doc/draft-palmero-ivy-ps-almo/) and [DMALMO](https://datatracker.ietf.org/doc/draft-palmero-ivy-dmalmo/) drafts would like to open this issue, to get consensus on the terminology we are using to address asset, feature, and entitlement.

The TM Forum (TMF) provides a comprehensive framework, known as Frameworx, which includes a Business Process Framework (eTOM), an Information Framework (SID), and an Application Framework (TAM). These aspects of Frameworx establish a common language and reference for different elements of a service provider's operations, including assets, entitlements, and features.

- Asset: In the TMF context, an asset is a valuable resource owned or controlled by an organization. This can include physical assets like hardware, logical assets like software, or informational assets like data.

- Entitlement: In the TMF context, an entitlement usually refers to the rights or privileges that a specific user or customer has within a system or service or even to access a certain feature. These rights or privileges are typically based on the user's subscription or contract terms.

- Feature: In the TMF context, a feature refers to a specific functionality or capability that a product, service, or system offers. When a customer subscribes to a service, they are given certain entitlements to use specific features.

 
 
The relationship between these elements can be understood as follows:
An asset (e.g., a network infrastructure, software system, etc.) provides certain features (capabilities or functionalities). The users or customers of the service are given entitlements (rights or privileges) to use these features based on their subscription or contract terms.
For instance, a software system (asset) may have a data analysis capability (feature), and a user might have an entitlement to use this feature based on their subscription level.

**Comment by italobusi** [comment]
**[2024-09-11 Base Network Inventory weekly call](https://github.com/ietf-ivy-wg/network-inventory-yang/wiki/minutes-2024-09-11)**

Confirmed during the call
