### ISSUE TITLE
Wrong identity for software in the core YANG model

### ISSUE THREAD

**Issue by aguoietf** [ietf-ivy-wg/network-inventory-yang#47]
The YANG model refers to a non-existing identity "iana-hadware:software" while constraining the container software-specific-info.

    container software-specific-info {
      when "../class = 'ianahw:software'";
      description 
        "This container contains some attributes belong to
        software only.";
      uses software-specific-info-grouping;
      config false;
    }

It caused a yanglint error and needs to be fixed.
Since the software model is still being defined,  I'd propose to leave this container empty and leave it for the software model to augment, or even better, remove the container completely from the core model.

**Comment by italobusi** [comment]
**[2024-05-22 Network Inventory weekly call](https://github.com/ietf-ivy-wg/network-inventory-yang/wiki/minutes-2024-05-22)**

It is a bug to be fixed:
- remove the container software-specific-info from the model

- [ ] @aguoietf submit a PR to fix the bug
