### ISSUE TITLE
virtual NE vs. LNE (RFC8530)

### ISSUE THREAD

**Issue by boucadair** [ietf-ivy-wg/network-inventory-yang#56]
https://github.com/ietf-ivy-wg/network-inventory-yang/blob/d13257a88ddef39df709dd6dd803c9a9c3361302/draft-ietf-ivy-network-inventory-yang.md?plain=1#L265C1-L269C54

I suggest to position/align virtual NE vs. LNE per https://datatracker.ietf.org/doc/html/rfc8530#section-2

**Comment by italobusi** [comment]
@boucadair please consider the following comment: https://github.com/ietf-ivy-wg/network-inventory-yang/issues/35#issuecomment-2389017940

If LNEs are different from virtual NEs and outside the scope of IVY WG, I think we can keep the text as it is and close the issue

**Comment by lana-wu** [comment]
I agree with Italo that LNEs are functions configured on the devices which is out scope of IVY WG. 
For the virtual NEs, We have similar devices deployed: https://datatracker.ietf.org/doc/html/draft-ietf-bess-virtual-pe-00, which has an inventory of cards similar to the physical router and is managed by the same controller as the physical routers

**Comment by italobusi** [comment]
I have re-read the current text in the I-D and it looks to me quite generic and open to support any type of inventory object that can be managed as a network-element.

If the example text within the brackets '(e.g., virtual network elements)' is contentious, we can remove it, but I am ok to keep it as well.

IMHO, the definition of what is a virtual NE and why it has to be managed as a network element is outside the scope of this I-D and in the scope of the software inventory I-D.

**Comment by boucadair** [comment]
> I agree with Italo that LNEs are functions

Not sure to get this as RFC8530 says "An LNE is an independently managed virtual device made up of
   resources allocated to it from the host or parent network device."

**Comment by boucadair** [comment]
> If the example text within the brackets '(e.g., virtual network elements)' is contentious, we can remove it, but I am ok to keep it as well.

Add LNE as an example would work for me.

> and in the scope of the software inventory I-D

Deal. Let's clarify that in the software inventory I-D

**Comment by italobusi** [comment]
**[2024-10-16 Base Network Inventory weekly call](https://github.com/ietf-ivy-wg/network-inventory-yang/wiki/minutes-2024-10-16)**

There is no agreement that the LNE can be managed as a network-element as defined in the inventory model

The current text looks good enough and does not preclude defining new type of network-elements in other modules

If LNE is considered in the scope of IVY, a new I-D describing why LNE should be managed in the IVY (and defining an appropriate ne-type) can be submitted to IVY WG at any time

Agreed to close the issue with no changes to the current text
