### ISSUE TITLE
Software patch

### ISSUE THREAD

**Issue by italobusi** [ietf-ivy-wg/network-inventory-yang#6]
Whether the software patch is in the base inventory model is to be discussed.

**Comment by YuChaode** [comment]
[Modeling of Patch Software.pptx](https://github.com/ietf-ivy-wg/network-inventory-yang/files/14352759/Modeling.of.Patch.Software.pptx)
a slide to  be discussed on 21st Feb meeting.

**Comment by italobusi** [comment]
**[2024-03-06 Base Network Inventory weekly call](https://github.com/ietf-ivy-wg/network-inventory-yang/blob/main/minutes/minutes-2024-03-06.md)**

Proposal from Chaode discussed: https://github.com/ietf-ivy-wg/network-inventory-yang/files/14352759/Modeling.of.Patch.Software.pptx

Agreement reached to add a software-patch-rev attribute for the components

Note: the attribute name has been chosen to clarify that the patch is a SW patch and to align with the naming convention used for HW, FW and SW versions

Agreement to define the software-patch-rev attribute as a list

It has been discussed whether there is always a single SW instance per component or there could be multiple SW instances running on the same component

It was pointed out that the SW inventory extension model allows modelling the cases where multiple SW instances are running on the same HW component

The base model can support HW components that support a single SW module. Complex configurations where an HW component can support multiple SW versions can be modelled using the SW inventory extension model: in this case, an HW-only component instance will have only the hardware-rev and it will contain one or more SW-only child component instances, which will have only the software-rev attribute

Agreement to keep only onw software-rev attribute per component

Agreement to add the software-patch-rev attribute (as a list) also for network elements

- [ ] @YuChaode  update the YANG model and the draft as agreed during the call
