### ISSUE TITLE
Presentation at IETF 121

### ISSUE THREAD

**Issue by italobusi** [ietf-ivy-wg/network-inventory-yang#67]

**Comment by YuChaode** [comment]
[draft-ietf-ivy-network-inventory-yang.pptx](https://github.com/user-attachments/files/17611801/draft-ietf-ivy-network-inventory-yang.pptx)

**Comment by italobusi** [comment]
Presentation uploaded on datatracker: https://datatracker.ietf.org/doc/slides-121-ivy-a-yang-data-model-for-network-inventory/
